// This file was automatically generated by jinjaroot. Do not edit directly.
import { DaemonVersion } from "./kachery-js/types/kacheryTypes"

const VERSION = 'kachery-daemon-1.0.15' as any as DaemonVersion

export default VERSION