// This file was automatically generated by jinjaroot. Do not edit directly.
import { DaemonVersion } from "commonInterface/kacheryTypes"

const VERSION = 'kachery-daemon-1.0.27' as any as DaemonVersion

export default VERSION