// This file was automatically generated by jinjaroot. Do not edit directly.
import { DaemonVersion } from "./common/types/kacheryTypes"

const VERSION = 'kachery-daemon-1.0.0' as any as DaemonVersion

export default VERSION